sudo: false
language: scala
scala:
  - 2.11.1
jdk:
  - oraclejdk8
services:
  - mongodb
cache:
  directories:
    - '$HOME/.ivy2/cache'
deploy:
  - provider: heroku
    api_key:
      secure: t7ehgv2w2FSPlptKKtDAfmqVRfhdwB07/lZl2RWWBrsf40KYIoITpj0FwzG7UMjHW27whR/j/rnx0qftjX9L8BD3VmdNBIMUAT5iI5N145GrB5pW/ipFQYmYtPNheEtfLbFrwazaYL4Nllyo5uro3DWrWtXxj1K7wBNRhHVbmtE=
    app: field-register
    on:
      repo: openregister/register
