sudo: false
language: scala
scala:
  - 2.11.6
jdk:
  - oraclejdk8
services:
  - mongodb
addons:
  postgresql: "9.4"
cache:
  directories:
    - '$HOME/.ivy2/cache'
before_script:
  - psql -c 'create database testopenregister;' -U postgres
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
