sudo: false
language: scala
scala:
  - 2.11.6
jdk:
  - oraclejdk8
services:
  - mongodb
addons:
  postgresql: "9.4"
cache:
  directories:
    - '$HOME/.ivy2/cache'
before_script:
  - psql -c 'create database testopenregister;' -U postgres
-deploy:
-  - provider: heroku
-    api_key:
-      secure: t7ehgv2w2FSPlptKKtDAfmqVRfhdwB07/lZl2RWWBrsf40KYIoITpj0FwzG7UMjHW27whR/j/rnx0qftjX9L8BD3VmdNBIMUAT5iI5N145GrB5pW/ipFQYmYtPNheEtfLbFrwazaYL4Nllyo5uro3DWrWtXxj1K7wBNRhHVbmtE=
-    app: register
-    on:
-      repo: openregister/register
-deploy:
-  - provider: heroku
-    api_key:
-      secure: t7ehgv2w2FSPlptKKtDAfmqVRfhdwB07/lZl2RWWBrsf40KYIoITpj0FwzG7UMjHW27whR/j/rnx0qftjX9L8BD3VmdNBIMUAT5iI5N145GrB5pW/ipFQYmYtPNheEtfLbFrwazaYL4Nllyo5uro3DWrWtXxj1K7wBNRhHVbmtE=
-    app: school
-    on:
-      repo: openregister/register
-deploy:
-  - provider: heroku
-    api_key:
-      secure: t7ehgv2w2FSPlptKKtDAfmqVRfhdwB07/lZl2RWWBrsf40KYIoITpj0FwzG7UMjHW27whR/j/rnx0qftjX9L8BD3VmdNBIMUAT5iI5N145GrB5pW/ipFQYmYtPNheEtfLbFrwazaYL4Nllyo5uro3DWrWtXxj1K7wBNRhHVbmtE=
-    app: address
-    on:
-      repo: openregister/register
