sudo: false
language: scala
scala:
  - 2.11.6
jdk:
  - oraclejdk8
services:
  - mongodb
addons:
  postgresql: "9.4"
cache:
  directories:
    - '$HOME/.ivy2/cache'
before_script:
  - psql -c 'create database testopenregister;' -U postgres
